03. 자바스크립트 개발 환경과 실행 방법
KHU-JS-Study/javascript-study pull request #22
Opened 2023-01-24 09:32 UTC by BARAM1NG

# 03. 자바스크립트 개발 환경과 실행 방법

## ✏️ 기억에 남는 내용

- 브라우저는 클라이언트 사이드 Web API를 지원하고, Node.js는 고유의 API를 지원한다.
- VS Code에서는 확장 플러그인 저장소인 "마켓플레이스"를 통해 다양한 확장 플러그인을 다운로드해서 설치할 수 있다.
- 클라이언트 사이드 Web API가 포함된 자바스크립트 코드를 실행하려면 Node.js 환경이 아닌 브라우저에서 실행해야한다.

<br />

## 📝 간단한 퀴즈

- 자바스크립트 코드를 실행할 때, 줄바꿈이 필요한 경우 단축키는?

<br />

## 🧑🏻‍💻 연관 코드
```javascript
// 관련 코드를 적어주세요.
```

2023-01-24 12:59 UTC, L2HYUNN approved these changes
LGTM

2023-01-30 11:59 UTC, Sun4-me commented on 1주차 (01~04장)/03. 자바스크립트 개발 환경과 실행 방법/간단한 퀴즈.md
> +- 자바스크립트 코드를 실행할 때, 줄바꿈이 필요한 경우의 단축키는?
Shifr + Enter

2023-01-30 11:59 UTC, Sun4-me approved these changes
LGTM

2023-01-30 16:37 UTC, LSH-0125 approved these changes
파일 생성하실 때 아람님 폴더를 만들고 그 안에 공부한 내용들의 파일을 생성하는 것이 더 통일성에 맞을 것 같습니다 ! 
Files changed 에서 파일 경로를 다른 분들과 비교해보시면 이해가 빠르실겁니다 !

2023-01-30 16:48 UTC, LSH-0125 requested changes
파일 생성하실 때 아람님 폴더를 만들고 그 안에 공부한 내용들의 파일을 생성하는 것이 더 통일성에 맞을 것 같습니다 !
Files changed 에서 파일 경로를 다른 분들과 비교해보시면 이해가 빠르실겁니다 !

2023-01-31 12:26 UTC, LSH-0125 approved these changes
LGTM

2023-01-31 13:15 UTC, merged